// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlxafeaddhmlzdfticla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRseGFmZWFkZGhtbHpkZnRpY2xhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTM3OTUsImV4cCI6MjA3Mzg2OTc5NX0.ya305JFAH3I1mA2lhyAgsKDIGA_Xnkqe1xpluKFHxLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});